Feat plugins page
dev-protocol/clubsx pull request #118
Opened 2022-09-08 03:49 UTC by 0xdutc

#### Description of the change

- Add the central section for the plugins page.

#### Screenshots

#### Checklist
- [x] Display dynamic plugins
- [x] Toggle activation status of plugins

**I agree to the following :-**

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/WebXDAO/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**):

2022-09-08 04:26 UTC, aggre requested changes

2022-09-08 04:26 UTC, aggre commented on src/plugins/admin/plugins.astro
> +<AdminPlugins client:only="react" plugins={allPlugins} />
For enumerate plugins, refer to `Astro.props.clubs.plugins` instead of `Astro.props.clubs.encodedClubsConfiguration`.

clubs.encodedClubsConfiguration is a user preference list and unconfigured plugins are not included in it. clubs.plugins is the "all installed plugins" list.

Enumerate the plugins in clubs.plugins and refer to the decoded clubs.encodedClubsConfiguration.plugins[] to see the initial enabled/disabled values.

2022-09-08 04:26 UTC, aggre commented on src/components/AdminPlugins/AdminPlugins.jsx
> +  constructor(props) {
AdimnPlugins should receive the return value of `decode(clubs.encodedClubsConfiguration)` or receive the `clubs.encodedClubsConfiguration` string and decode it in this component.

This is because AdimnPlugins needs to call `setConfig(a_new_config)` when toggled the plugin.

2022-09-08 04:26 UTC, aggre commented on src/components/AdminPlugins/AdminPlugins.jsx
> +  }
Disable/Enabled switches doesn't seem to be reactive. Can you update the switch UIs every time the user toggle it?

2022-09-08 04:26 UTC, aggre commented on src/components/AdminPlugins/AdminPlugins.jsx
> +  }
This function should call `setConfig` internally. setConfig requires passing the complete ClubsConfiguration.

So, toggle `plugins[].enabled` on the decoded clubs.encodedClubsConfiguration and pass the new ClubsConfiguration object to setConfig.

2022-09-09 02:13 UTC, 0xdutc commented on src/components/AdminPlugins/AdminPlugins.jsx
> +  }
It was already added in, however there were 2 state updates triggering hence cancelling out the toggle. I've fixed it now.

2022-09-09 04:09 UTC, aggre approved these changes
Works perfectly now!

2022-09-09 04:09 UTC, merged